### ISSUE TITLE
Error -> missing dependency 'date-fns-tz/esm'

### ISSUE THREAD

**Issue by the-ult** [sapozhnikovay/ngx-mat-datefns-date-adapter#7] opened 2021-05-25 08:54 UTC
When installing `ngx-mat-datefns-date-adapter` I was getting the following error:

```
 Error: The target entry-point "ngx-mat-datefns-date-adapter" has missing dependencies:  - date-fns-tz/esm
```

Had to install [date-fns-tz](https://github.com/marnusw/date-fns-tz) as a dependency next to `date-fns` itself.

Is this correct? Did not see it in the Readme or on the [Stackblitz Example](https://stackblitz.com/edit/angular-ngx-mat-datefns-date-adapter-a11-es-locales?file=package.json)

Using:
```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : darwin x64
  npm  : 6.14.13
  
  @nrwl/angular : 12.3.3
  @nrwl/cli : 12.3.3
  @nrwl/cypress : 12.3.3
  @nrwl/devkit : 12.3.3
  @nrwl/eslint-plugin-nx : 12.3.3
  @nrwl/express : 12.3.3
  @nrwl/jest : 12.3.3
  @nrwl/linter : 12.3.3
  @nrwl/node : 12.3.3
  @nrwl/tao : 12.3.3
  @nrwl/workspace : 12.3.3
  typescript : 4.2.4

  "@angular/animations": "12.0.0",
  "@angular/cdk": "12.0.0",
  "@angular/common": "12.0.0",
  "@angular/compiler": "12.0.0",
  "@angular/core": "12.0.0",
  "@angular/forms": "12.0.0",
  "@angular/material": "12.0.0",
  "@angular/platform-browser": "12.0.0",
  "@angular/platform-browser-dynamic": "12.0.0",
  "@angular/router": "12.0.0",
```

```
● Test suite failed to run

    Cannot find module 'date-fns-tz/esm' from '../../node_modules/ngx-mat-datefns-date-adapter/bundles/ngx-mat-datefns-date-adapter.umd.js'

    Require stack:
    .../node_modules/ngx-mat-datefns-date-adapter/bundles/ngx-mat-datefns-date-adapter.umd.js
      src/app/my-app.module.ts
      src/app/my-app.component.spec.ts

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:306:11)
      at ../../node_modules/ngx-mat-datefns-date-adapter/bundles/ngx-mat-datefns-date-adapter.umd.js:2:167
      at Object.<anonymous> (../../node_modules/ngx-mat-datefns-date-adapter/bundles/ngx-mat-datefns-date-adapter.umd.js:5:2)
```

**Comment by the-ult** [comment] 2021-05-25 17:29
hmmm..
Might have been due to wrong import:
`import { nl } from 'date-fns/esm/locale/nl';`

**Comment by the-ult** [comment] 2021-05-25 18:36
When `date-fns-tz` is installed, I get the following error, running a test:

```
● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/ultimate-solutions/tkp/vernieuwing-db/dpf-backoffice/node_modules/date-fns-tz/esm/index.js:3
    export { default as format } from './format/index.js'
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1350:14)
      at ../../node_modules/ngx-mat-datefns-date-adapter/bundles/ngx-mat-datefns-date-adapter.umd.js:2:192
      at Object.<anonymous> (../../node_modules/ngx-mat-datefns-date-adapter/bundles/ngx-mat-datefns-date-adapter.umd.js:5:2)
```

**Comment by sapozhnikovay** [comment] 2021-05-25 20:52
@the-ult Hello.

Looks like you are missing both `date-fns` and `date-fns-tz` installed. These libraries are marked as a Peer dependencies in ngx-mat-datefns-date-adapter package.  Maybe I should add this info the README )

After install of ngx-mat-datefsn-date-adapter package on a clean Angular 12 install with Material I get these warnings:

```
npm WARN ngx-mat-datefns-date-adapter@11.2.0 requires a peer of @angular/common@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-mat-datefns-date-adapter@11.2.0 requires a peer of @angular/core@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-mat-datefns-date-adapter@11.2.0 requires a peer of @angular/material@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-mat-datefns-date-adapter@11.2.0 requires a peer of date-fns@^2.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-mat-datefns-date-adapter@11.2.0 requires a peer of date-fns-tz@^1.1.4 but none is installed. You must install peer dependencies yourself.
```

And only after install of both `date-fns` and `date-fns-tz` packages I can successfully compile my app.

Please, add both libraries via npm install and check the tests.
If you will encounter further difficulties, please send me a reproduction (on Stackblitz for example).

**Comment by the-ult** [comment] 2021-05-25 21:00
Thanks.

Adding them to the README might be a good idea :-)
Somehow missed the warnings. (while I normally check them).

**Comment by sapozhnikovay** [comment] 2021-05-30 18:41
I've updated install section in the **README** with the info about `date-fns` and `date-fns-tz` peer dependencies.

**Closed by sapozhnikovay** 2021-05-30 18:41 UTC
Labels: question
